bamPath: /mnt/lustre/groups/herv_project/BAMs/
cramPath:  /home/projectmine-mkooyman/STEAK/
outPath: results/
HERVK_ref: resources/HERVK_ref.fasta
novoindex: /home/projectmine-mkooyman/STEAK/novoindex
knownNR: resources/list_of_known_integration_sites.bed
pythonScripts: pythonScripts
hg19ref: /cvmfs/softdrive.nl/projectmine_sw/resources/Build38/hs38DH/hs38DH.fa
